spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  mvc:
    view:
      prefix: /templates/views/
      suffix: .jsp
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:migrations
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
